# Generated by Django 3.2.7 on 2021-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_arms', '0006_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment'),
        ),
    ]
