# Generated by Django 3.2.5 on 2021-09-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLike',
            new_name='Like',
        ),
    ]
