# Generated by Django 3.2.5 on 2021-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210824_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
