# Generated by Django 3.2.7 on 2021-10-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_arms', '0002_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
