# Generated by Django 3.2.5 on 2021-09-30 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210930_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
